### ISSUE TITLE
Increase signal duration?

### ISSUE THREAD

**Issue by jamiesteven** [tessel/ir-attx4#37]
I've seen #21; I have a Mitshibishi Mini Split which seems to have pretty long IR signals: https://github.com/r45635/HVAC-IR-Control/blob/master/Protocol/Mitsubishi_IR_Packet_Data_v1.0-FULL.pdf

I was curious if there's anyway to increase the 200 byte maximum for the IR module?

**Comment by johnnyman727** [comment]
@jamiesteven good question. It is possible but I wouldn't recommend it. Basically, you would just change the size of the receive buffer and reflash the device. Unfortunately, I found experimentally that an allocation over 200 bytes often resulted in the stack corrupting the heap and the device crashing.

**Comment by jamiesteven** [comment]
@johnnyman727 Thanks very much for replying. Bummed at Mitsubishi for using IR codes that are so long. It's a shame there isn't a good alternative for sending complex IR codes -- doing IR is a mess on RaspPi and Arduino.

**Comment by olivierpichon** [comment]
Hi @johnnyman727, thanks heaps for the great work on this infrared library!

I am a JS developer with interest for IoT (but really lacking from low level knowledge) and I was wondering if you could give more details as to why we have this buffer overflow?

Is it because the IR module has its own memory / registers that has a very limited size that we hit when receiving too much information? If that's the case (and maybe that's complete madness so apologies in advance) but could we transmit this data back to the RAM of the tessel device?

I originally bought the tessel IR module to switch off and on my aircon and because it needs to transmit a lot of information, I can't use the module :( 

Thanks again for your time and effort and merry Christmas from really hot Australia! ^_^

**Comment by johnnyman727** [comment]
Hi @olivierpichon, thanks for your interest!

> Is it because the IR module has its own memory / registers that has a very limited size that we hit when receiving too much information?

Yes, that's exactly the issue here. There is a microcontroller on the module called the ATTINY84. True to its name, it is tiny in size and available memory. Increasing the allocated memory for the buffer we use to save incoming data would likely lead to a recurring crash as the heap grows into the stack.

 > could we transmit this data back to the RAM of the tessel device?

That's a good suggestion but I don't think it would be possible. The module would need to alert the Tessel that its buffer was full, have Tessel service that interrupt, and transfer that data all before the next IR signal is received (to avoid any data loss). Unfortunately, the timespan between IR signals is on the order of microseconds and the timespan for communication with the Tessel is on the order of tens of milliseconds. The system is just not capable to responding quickly enough.

> I originally bought the tessel IR module to switch off and on my aircon and because it needs to transmit a lot of information, I can't use the module :(

I'm really sorry to hear that, friend! It was challenging to build a simple, cost-effective module that could work across a wide range of aircons and it looks like we weren't able to hit that target for you.

If you only need to transmit data to your aircon and are feeling like learning more about low level development, you could potentially double your [available transmit buffer size](https://github.com/tessel/ir-attx4/blob/master/firmware/include/infrared-attx4.h#L61) by [deleting the receive buffer](https://github.com/tessel/ir-attx4/blob/master/firmware/include/infrared-attx4.h#L80-L87). It won't be super easy and I'm not sure if a 200 byte buffer is sufficient to transmit one packet for your model of aircon, but it's an option!

**Comment by olivierpichon** [comment]
@johnnyman727 thank you so much for this amazing answer, it makes total sense. It is far from my comfort zone, but I will give it a fair go at deleting the received buffer.

BTW, happy new year and thanks for the awesome work!! 🎉 🎉 🎉
